theme: jekyll-theme-minimal
logo: https://avatars.githubusercontent.com/u/62823952?v=4&size=128
title : Yue's Home Page | 5i03
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
